# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from specter.proto import specter_pb2 as specter_dot_proto_dot_specter__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in specter/proto/specter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PreviewerServiceStub(object):
    """----------------------------- PreviewerService ---------------------------- //

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListenPreview = channel.unary_stream(
                '/specter_proto.PreviewerService/ListenPreview',
                request_serializer=specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
                response_deserializer=specter_dot_proto_dot_specter__pb2.PreviewImage.FromString,
                _registered_method=True)


class PreviewerServiceServicer(object):
    """----------------------------- PreviewerService ---------------------------- //

    """

    def ListenPreview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreviewerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListenPreview': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenPreview,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.ObjectId.FromString,
                    response_serializer=specter_dot_proto_dot_specter__pb2.PreviewImage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'specter_proto.PreviewerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('specter_proto.PreviewerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PreviewerService(object):
    """----------------------------- PreviewerService ---------------------------- //

    """

    @staticmethod
    def ListenPreview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/specter_proto.PreviewerService/ListenPreview',
            specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
            specter_dot_proto_dot_specter__pb2.PreviewImage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MarkerServiceStub(object):
    """------------------------------ MarkerService ------------------------------ //

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/specter_proto.MarkerService/Start',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/specter_proto.MarkerService/Stop',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class MarkerServiceServicer(object):
    """------------------------------ MarkerService ------------------------------ //

    """

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'specter_proto.MarkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('specter_proto.MarkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarkerService(object):
    """------------------------------ MarkerService ------------------------------ //

    """

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.MarkerService/Start',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.MarkerService/Stop',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RecorderServiceStub(object):
    """----------------------------- RecorderService ----------------------------- //

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListenCommands = channel.unary_stream(
                '/specter_proto.RecorderService/ListenCommands',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=specter_dot_proto_dot_specter__pb2.RecorderCommand.FromString,
                _registered_method=True)


class RecorderServiceServicer(object):
    """----------------------------- RecorderService ----------------------------- //

    """

    def ListenCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecorderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListenCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenCommands,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=specter_dot_proto_dot_specter__pb2.RecorderCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'specter_proto.RecorderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('specter_proto.RecorderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecorderService(object):
    """----------------------------- RecorderService ----------------------------- //

    """

    @staticmethod
    def ListenCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/specter_proto.RecorderService/ListenCommands',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            specter_dot_proto_dot_specter__pb2.RecorderCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MouseServiceStub(object):
    """------------------------------ MouseService ------------------------------- //

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Click = channel.unary_unary(
                '/specter_proto.MouseService/Click',
                request_serializer=specter_dot_proto_dot_specter__pb2.MouseClick.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Move = channel.unary_unary(
                '/specter_proto.MouseService/Move',
                request_serializer=specter_dot_proto_dot_specter__pb2.MouseMove.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Scroll = channel.unary_unary(
                '/specter_proto.MouseService/Scroll',
                request_serializer=specter_dot_proto_dot_specter__pb2.MouseScroll.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ClickObject = channel.unary_unary(
                '/specter_proto.MouseService/ClickObject',
                request_serializer=specter_dot_proto_dot_specter__pb2.ObjectMouseClick.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.MoveOverObject = channel.unary_unary(
                '/specter_proto.MouseService/MoveOverObject',
                request_serializer=specter_dot_proto_dot_specter__pb2.ObjectMouseMove.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class MouseServiceServicer(object):
    """------------------------------ MouseService ------------------------------- //

    """

    def Click(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scroll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClickObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveOverObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MouseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Click': grpc.unary_unary_rpc_method_handler(
                    servicer.Click,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.MouseClick.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.MouseMove.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Scroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Scroll,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.MouseScroll.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ClickObject': grpc.unary_unary_rpc_method_handler(
                    servicer.ClickObject,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.ObjectMouseClick.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'MoveOverObject': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveOverObject,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.ObjectMouseMove.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'specter_proto.MouseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('specter_proto.MouseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MouseService(object):
    """------------------------------ MouseService ------------------------------- //

    """

    @staticmethod
    def Click(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.MouseService/Click',
            specter_dot_proto_dot_specter__pb2.MouseClick.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.MouseService/Move',
            specter_dot_proto_dot_specter__pb2.MouseMove.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.MouseService/Scroll',
            specter_dot_proto_dot_specter__pb2.MouseScroll.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClickObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.MouseService/ClickObject',
            specter_dot_proto_dot_specter__pb2.ObjectMouseClick.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveOverObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.MouseService/MoveOverObject',
            specter_dot_proto_dot_specter__pb2.ObjectMouseMove.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class KeyboardServiceStub(object):
    """---------------------------- KeyboardService ------------------------------ //

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.KeyPress = channel.unary_unary(
                '/specter_proto.KeyboardService/KeyPress',
                request_serializer=specter_dot_proto_dot_specter__pb2.KeyEvent.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.KeyRelease = channel.unary_unary(
                '/specter_proto.KeyboardService/KeyRelease',
                request_serializer=specter_dot_proto_dot_specter__pb2.KeyEvent.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.TypeText = channel.unary_unary(
                '/specter_proto.KeyboardService/TypeText',
                request_serializer=specter_dot_proto_dot_specter__pb2.TextInput.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.TypeIntoObject = channel.unary_unary(
                '/specter_proto.KeyboardService/TypeIntoObject',
                request_serializer=specter_dot_proto_dot_specter__pb2.ObjectTextInput.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class KeyboardServiceServicer(object):
    """---------------------------- KeyboardService ------------------------------ //

    """

    def KeyPress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KeyRelease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TypeText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TypeIntoObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyboardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'KeyPress': grpc.unary_unary_rpc_method_handler(
                    servicer.KeyPress,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.KeyEvent.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'KeyRelease': grpc.unary_unary_rpc_method_handler(
                    servicer.KeyRelease,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.KeyEvent.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TypeText': grpc.unary_unary_rpc_method_handler(
                    servicer.TypeText,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.TextInput.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TypeIntoObject': grpc.unary_unary_rpc_method_handler(
                    servicer.TypeIntoObject,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.ObjectTextInput.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'specter_proto.KeyboardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('specter_proto.KeyboardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyboardService(object):
    """---------------------------- KeyboardService ------------------------------ //

    """

    @staticmethod
    def KeyPress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.KeyboardService/KeyPress',
            specter_dot_proto_dot_specter__pb2.KeyEvent.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KeyRelease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.KeyboardService/KeyRelease',
            specter_dot_proto_dot_specter__pb2.KeyEvent.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TypeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.KeyboardService/TypeText',
            specter_dot_proto_dot_specter__pb2.TextInput.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TypeIntoObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.KeyboardService/TypeIntoObject',
            specter_dot_proto_dot_specter__pb2.ObjectTextInput.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ObjectServiceStub(object):
    """----------------------------- ObjectService ------------------------------- //

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTree = channel.unary_unary(
                '/specter_proto.ObjectService/GetTree',
                request_serializer=specter_dot_proto_dot_specter__pb2.OptionalObjectId.SerializeToString,
                response_deserializer=specter_dot_proto_dot_specter__pb2.ObjectTree.FromString,
                _registered_method=True)
        self.Find = channel.unary_unary(
                '/specter_proto.ObjectService/Find',
                request_serializer=specter_dot_proto_dot_specter__pb2.ObjectSearchQuery.SerializeToString,
                response_deserializer=specter_dot_proto_dot_specter__pb2.ObjectIds.FromString,
                _registered_method=True)
        self.GetObjectQuery = channel.unary_unary(
                '/specter_proto.ObjectService/GetObjectQuery',
                request_serializer=specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
                response_deserializer=specter_dot_proto_dot_specter__pb2.ObjectSearchQuery.FromString,
                _registered_method=True)
        self.GetParent = channel.unary_unary(
                '/specter_proto.ObjectService/GetParent',
                request_serializer=specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
                response_deserializer=specter_dot_proto_dot_specter__pb2.ObjectId.FromString,
                _registered_method=True)
        self.GetChildren = channel.unary_unary(
                '/specter_proto.ObjectService/GetChildren',
                request_serializer=specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
                response_deserializer=specter_dot_proto_dot_specter__pb2.ObjectIds.FromString,
                _registered_method=True)
        self.CallMethod = channel.unary_unary(
                '/specter_proto.ObjectService/CallMethod',
                request_serializer=specter_dot_proto_dot_specter__pb2.MethodCall.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateProperty = channel.unary_unary(
                '/specter_proto.ObjectService/UpdateProperty',
                request_serializer=specter_dot_proto_dot_specter__pb2.PropertyUpdate.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetMethods = channel.unary_unary(
                '/specter_proto.ObjectService/GetMethods',
                request_serializer=specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
                response_deserializer=specter_dot_proto_dot_specter__pb2.Methods.FromString,
                _registered_method=True)
        self.GetProperties = channel.unary_unary(
                '/specter_proto.ObjectService/GetProperties',
                request_serializer=specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
                response_deserializer=specter_dot_proto_dot_specter__pb2.Properties.FromString,
                _registered_method=True)
        self.ListenTreeChanges = channel.unary_stream(
                '/specter_proto.ObjectService/ListenTreeChanges',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=specter_dot_proto_dot_specter__pb2.TreeChange.FromString,
                _registered_method=True)
        self.ListenPropertiesChanges = channel.unary_stream(
                '/specter_proto.ObjectService/ListenPropertiesChanges',
                request_serializer=specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
                response_deserializer=specter_dot_proto_dot_specter__pb2.PropertyChange.FromString,
                _registered_method=True)


class ObjectServiceServicer(object):
    """----------------------------- ObjectService ------------------------------- //

    """

    def GetTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Find(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObjectQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChildren(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMethods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenTreeChanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenPropertiesChanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTree,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.OptionalObjectId.FromString,
                    response_serializer=specter_dot_proto_dot_specter__pb2.ObjectTree.SerializeToString,
            ),
            'Find': grpc.unary_unary_rpc_method_handler(
                    servicer.Find,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.ObjectSearchQuery.FromString,
                    response_serializer=specter_dot_proto_dot_specter__pb2.ObjectIds.SerializeToString,
            ),
            'GetObjectQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObjectQuery,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.ObjectId.FromString,
                    response_serializer=specter_dot_proto_dot_specter__pb2.ObjectSearchQuery.SerializeToString,
            ),
            'GetParent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParent,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.ObjectId.FromString,
                    response_serializer=specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
            ),
            'GetChildren': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChildren,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.ObjectId.FromString,
                    response_serializer=specter_dot_proto_dot_specter__pb2.ObjectIds.SerializeToString,
            ),
            'CallMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.CallMethod,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.MethodCall.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProperty,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.PropertyUpdate.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMethods,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.ObjectId.FromString,
                    response_serializer=specter_dot_proto_dot_specter__pb2.Methods.SerializeToString,
            ),
            'GetProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperties,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.ObjectId.FromString,
                    response_serializer=specter_dot_proto_dot_specter__pb2.Properties.SerializeToString,
            ),
            'ListenTreeChanges': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenTreeChanges,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=specter_dot_proto_dot_specter__pb2.TreeChange.SerializeToString,
            ),
            'ListenPropertiesChanges': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenPropertiesChanges,
                    request_deserializer=specter_dot_proto_dot_specter__pb2.ObjectId.FromString,
                    response_serializer=specter_dot_proto_dot_specter__pb2.PropertyChange.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'specter_proto.ObjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('specter_proto.ObjectService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObjectService(object):
    """----------------------------- ObjectService ------------------------------- //

    """

    @staticmethod
    def GetTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.ObjectService/GetTree',
            specter_dot_proto_dot_specter__pb2.OptionalObjectId.SerializeToString,
            specter_dot_proto_dot_specter__pb2.ObjectTree.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Find(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.ObjectService/Find',
            specter_dot_proto_dot_specter__pb2.ObjectSearchQuery.SerializeToString,
            specter_dot_proto_dot_specter__pb2.ObjectIds.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetObjectQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.ObjectService/GetObjectQuery',
            specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
            specter_dot_proto_dot_specter__pb2.ObjectSearchQuery.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.ObjectService/GetParent',
            specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
            specter_dot_proto_dot_specter__pb2.ObjectId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChildren(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.ObjectService/GetChildren',
            specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
            specter_dot_proto_dot_specter__pb2.ObjectIds.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.ObjectService/CallMethod',
            specter_dot_proto_dot_specter__pb2.MethodCall.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.ObjectService/UpdateProperty',
            specter_dot_proto_dot_specter__pb2.PropertyUpdate.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.ObjectService/GetMethods',
            specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
            specter_dot_proto_dot_specter__pb2.Methods.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_proto.ObjectService/GetProperties',
            specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
            specter_dot_proto_dot_specter__pb2.Properties.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenTreeChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/specter_proto.ObjectService/ListenTreeChanges',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            specter_dot_proto_dot_specter__pb2.TreeChange.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenPropertiesChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/specter_proto.ObjectService/ListenPropertiesChanges',
            specter_dot_proto_dot_specter__pb2.ObjectId.SerializeToString,
            specter_dot_proto_dot_specter__pb2.PropertyChange.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
