# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from specter_debugger.proto import specter_pb2 as specter__debugger_dot_proto_dot_specter__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in specter_debugger/proto/specter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DebuggerServiceStub(object):
    """---------------------------- DebuggerService ------------------------------ //

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/specter_debugger_proto.DebuggerService/CreateSession',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=specter__debugger_dot_proto_dot_specter__pb2.Session.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/specter_debugger_proto.DebuggerService/ListSessions',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=specter__debugger_dot_proto_dot_specter__pb2.Sessions.FromString,
                _registered_method=True)
        self.SetSource = channel.unary_unary(
                '/specter_debugger_proto.DebuggerService/SetSource',
                request_serializer=specter__debugger_dot_proto_dot_specter__pb2.SourceSet.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/specter_debugger_proto.DebuggerService/Start',
                request_serializer=specter__debugger_dot_proto_dot_specter__pb2.Session.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/specter_debugger_proto.DebuggerService/Resume',
                request_serializer=specter__debugger_dot_proto_dot_specter__pb2.Session.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/specter_debugger_proto.DebuggerService/Pause',
                request_serializer=specter__debugger_dot_proto_dot_specter__pb2.Session.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/specter_debugger_proto.DebuggerService/Stop',
                request_serializer=specter__debugger_dot_proto_dot_specter__pb2.Session.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AddBreakpoint = channel.unary_unary(
                '/specter_debugger_proto.DebuggerService/AddBreakpoint',
                request_serializer=specter__debugger_dot_proto_dot_specter__pb2.BreakpointAdd.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveBreakpoint = channel.unary_unary(
                '/specter_debugger_proto.DebuggerService/RemoveBreakpoint',
                request_serializer=specter__debugger_dot_proto_dot_specter__pb2.BreakpointRemove.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetBreakpoints = channel.unary_unary(
                '/specter_debugger_proto.DebuggerService/GetBreakpoints',
                request_serializer=specter__debugger_dot_proto_dot_specter__pb2.Session.SerializeToString,
                response_deserializer=specter__debugger_dot_proto_dot_specter__pb2.Breakpoints.FromString,
                _registered_method=True)
        self.ListenEvents = channel.unary_stream(
                '/specter_debugger_proto.DebuggerService/ListenEvents',
                request_serializer=specter__debugger_dot_proto_dot_specter__pb2.Session.SerializeToString,
                response_deserializer=specter__debugger_dot_proto_dot_specter__pb2.Event.FromString,
                _registered_method=True)


class DebuggerServiceServicer(object):
    """---------------------------- DebuggerService ------------------------------ //

    """

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBreakpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveBreakpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBreakpoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DebuggerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=specter__debugger_dot_proto_dot_specter__pb2.Session.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=specter__debugger_dot_proto_dot_specter__pb2.Sessions.SerializeToString,
            ),
            'SetSource': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSource,
                    request_deserializer=specter__debugger_dot_proto_dot_specter__pb2.SourceSet.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=specter__debugger_dot_proto_dot_specter__pb2.Session.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=specter__debugger_dot_proto_dot_specter__pb2.Session.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=specter__debugger_dot_proto_dot_specter__pb2.Session.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=specter__debugger_dot_proto_dot_specter__pb2.Session.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddBreakpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBreakpoint,
                    request_deserializer=specter__debugger_dot_proto_dot_specter__pb2.BreakpointAdd.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveBreakpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveBreakpoint,
                    request_deserializer=specter__debugger_dot_proto_dot_specter__pb2.BreakpointRemove.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetBreakpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBreakpoints,
                    request_deserializer=specter__debugger_dot_proto_dot_specter__pb2.Session.FromString,
                    response_serializer=specter__debugger_dot_proto_dot_specter__pb2.Breakpoints.SerializeToString,
            ),
            'ListenEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenEvents,
                    request_deserializer=specter__debugger_dot_proto_dot_specter__pb2.Session.FromString,
                    response_serializer=specter__debugger_dot_proto_dot_specter__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'specter_debugger_proto.DebuggerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('specter_debugger_proto.DebuggerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DebuggerService(object):
    """---------------------------- DebuggerService ------------------------------ //

    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_debugger_proto.DebuggerService/CreateSession',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            specter__debugger_dot_proto_dot_specter__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_debugger_proto.DebuggerService/ListSessions',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            specter__debugger_dot_proto_dot_specter__pb2.Sessions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_debugger_proto.DebuggerService/SetSource',
            specter__debugger_dot_proto_dot_specter__pb2.SourceSet.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_debugger_proto.DebuggerService/Start',
            specter__debugger_dot_proto_dot_specter__pb2.Session.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_debugger_proto.DebuggerService/Resume',
            specter__debugger_dot_proto_dot_specter__pb2.Session.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_debugger_proto.DebuggerService/Pause',
            specter__debugger_dot_proto_dot_specter__pb2.Session.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_debugger_proto.DebuggerService/Stop',
            specter__debugger_dot_proto_dot_specter__pb2.Session.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBreakpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_debugger_proto.DebuggerService/AddBreakpoint',
            specter__debugger_dot_proto_dot_specter__pb2.BreakpointAdd.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveBreakpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_debugger_proto.DebuggerService/RemoveBreakpoint',
            specter__debugger_dot_proto_dot_specter__pb2.BreakpointRemove.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBreakpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specter_debugger_proto.DebuggerService/GetBreakpoints',
            specter__debugger_dot_proto_dot_specter__pb2.Session.SerializeToString,
            specter__debugger_dot_proto_dot_specter__pb2.Breakpoints.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/specter_debugger_proto.DebuggerService/ListenEvents',
            specter__debugger_dot_proto_dot_specter__pb2.Session.SerializeToString,
            specter__debugger_dot_proto_dot_specter__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
